_example/word_book_rails/config/routes.rb
Rails.application.routes.draw do
  get 'words/index'
  get 'words/show/:id', to: "words#show"
  get 'words/append'
  post 'words/create'
  get 'words/change'
  post 'words/update'
  get 'words/delete'
  delete 'words/exec_delete'
  get 'words/search'
  get 'words/list'
  root "words#index"
end

_example/word_book_rails/app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
  end

  def show
    begin
      @word = Word.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @word = nil
      flash.now[:alert] = "データベースにはid=#{params[:id]}のデータは登録されていません"
    end
  end    

  def append
    @en = @jp = ""
    set_append
  end

  def create
    @en = params[:word][:en]
    @jp = params[:word][:jp]
    @word = Word.new(en: @en, jp: @jp)
    if @word.save
      flash[:success] = "単語を保存しました"
      redirect_to "/words/show/#{@word.id}", status: :see_other
    else
      set_append
      flash.now[:alert] = "単語を保存できませんでした"
      render :append, status: :unprocessable_entity
    end
  end

  def change
    @en = @jp = ""
    set_change
  end

  def update
    @en = params[:word][:en]
    @jp = params[:word][:jp]
    @word = Word.find_by(en: @en)
    if @word == nil
      set_change
      flash.now[:alert] = "単語「#{@en}」は未登録のため変更できません"
      render :change, status: :unprocessable_entity
    elsif @word.update jp: @jp
      flash[:success] = "単語を変更しました"
      redirect_to "/words/show/#{@word.id}", status: :see_other
    else
      set_change
      flash.now[:alert] = "変更した単語を保存できませんでした"
      render :change, status: :unprocessable_entity
    end
  end

  def delete
    @delete_word = ""
  end

  def exec_delete
    @delete_word = params[:en]
    @word = Word.find_by(en: @delete_word)
    if @word == nil
      flash.now[:alert] = "単語#{@en}は未登録のため削除できません"
      render :delete, status: :unprocessable_entity
    else
      begin
        @word.destroy
      rescue
        flash[:alert] = "単語#{@en}を削除できませんでした"
      else
        flash[:success] = "単語を削除しました"
      end
      redirect_to words_index_path, status: :see_other
    end
  end

  def search
    @search_word = ""
  end

  def list
    @search_word = params[:en]
    if @search_word == ""
      flash.now[:alert] = "検索ワードは入力必須です"
      render :search, status: :unprocessable_entity
    end
    begin
      pattern = Regexp.compile(@search_word)
    rescue RegexpError
      flash.now[:alert] = "正規表現に構文エラーがあります"
      render :search, status: :unprocessable_entity
    else
      @words = Word.all.select{|word| word[:en] =~ pattern}.sort{|w1,w2| w1[:en] <=> w2[:en]}
    end
  end

  private

  def set_append
    @word = Word.new unless @word
    @path = words_create_path
    @submit = "作成"
  end
  def set_change
    @word = Word.new unless @word
    @path = words_update_path
    @submit = "変更"
  end
end

_example/word_book_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordBookRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <div class="col-sm-10 col-lg-8 col-xl-6 mx-auto">
        <%= render "navbar" %>
        <%= render "flash" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

_example/word_book_rails/app/views/words/_form.html.erb
<%= form_with model: @word, url: @path, method: :post do |form| %>
  <div>
    <%= form.label :en, "英単語", class: "form-label" %>
    <%= form.text_field :en, value: @en, class: "form-control" %>
    <% @word && @word.errors.full_messages_for(:en).each do |message| %>
      <div class="text-danger"><%= "DB: 英単語は空欄にできません" if message == "En can't be blank" %></div>
      <div class="text-danger"><%= "DB: 英文字を入力してください" if message == "En is invalid" %></div>
      <div class="text-danger"><%= "DB: すでに同名の単語が登録されています" if message == "En has already been taken" %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :jp, "日本語訳", class: "form-label" %>
    <%= form.text_field :jp, value: @jp, class: "form-control" %>
    <% @word && @word.errors.full_messages_for(:jp).each do |message| %>
      <div class="text-danger"><%= "DB: 日本語訳は空欄にできません" if message == "Jp can't be blank" %></div>
    <% end %>
  </div>

  <div class="my-2">
    <%= form.submit @submit,  class: "btn btn-primary" %>
  </div>
<% end %>

_example/word_book_rails/app/views/words/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Wordbook</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/words/append">Append</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/words/change">Change</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/words/delete">Delete</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/words/search">Search</a>
        </li>
    </div>
  </div>
</nav>

_example/word_book_rails/app/views/words/append.html.erb
<h1 class="my-2">単語登録</h1>
<%= render "form" %>

_example/word_book_rails/app/views/words/change.html.erb
<h1 class="my-2">単語の変更</h1>
<%= render "form" %>

_example/word_book_rails/app/views/words/delete.html.erb
<h1 class="my-2">単語削除</h1>
<%= form_with url: words_exec_delete_path, method: :delete do |form| %>
  <div>
    <%= form.label :en, "英単語", class: "form-label" %><br>
    <%= form.text_field :en, value: @delete_word, class: "form-control" %>
  </div>
  <div class="my-2">
    <%= form.submit "削除",  class: "btn btn-primary", data: {turbo_confirm: "Are you sure?"} %>
  </div>
<% end %>

_example/word_book_rails/app/views/words/index.html.erb
<h1 class="text-center">単語帳</h1>
<h5 class="my-2">単語帳の使い方</h5>
<ul class="list-group">
  <li class="list-group-item">Wordbook: 初期画面に戻ります</li>
  <li class="list-group-item">Append: 単語を追加します</li>
  <li class="list-group-item">Change: 登録済み単語を変更します</li>
  <li class="list-group-item">Delete: 単語を削除します</li>
  <li class="list-group-item">Search: 単語を検索しマッチした単語を表示します</li>
</ul>

_example/word_book_rails/app/views/words/list.html.erb
<h1 class="my-2">単語検索結果</h1>
<p>検索ワード: <%= @search_word %></p>
<% if @words %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">英語</th>
        <th scope="col">日本語</th>
      </tr>
    </thead>
    <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word[:en] %></td>
        <td><%= word[:jp] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

_example/word_book_rails/app/views/words/search.html.erb
  <h1 class="my-2">単語検索</h1>
  <%= form_with url: words_list_path, method: :get do |form| %>
    <div>
      <%= form.label :en, "英単語", class: "form-label" %><br>
      <%= form.text_field :en, value: @search_word, class: "form-control" %>
    </div>
    <div class="my-2">
      <%= form.submit "検索",  class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

_example/word_book_rails/app/views/words/show.html.erb
<% if @word %>
  <ul class="list-group">
    <li class="list-group-item"><%= @word.en %></li>
    <li class="list-group-item"><%= @word.jp %></li>
  </ul>
<% end %>