_example/word_book_rails_resources/config/routes.rb
Rails.application.routes.draw do
  root "words#index"
  get "words/search"
  resources :words
end

_example/word_book_rails_resources/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

_example/word_book_rails_resources/app/models/word.rb
class Word < ApplicationRecord
  validates :en, presence: true, format: {with: /[a-zA-Z]+/}, uniqueness: true
  validates :jp, presence: true
end

_example/word_book_rails_resources/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

_example/word_book_rails_resources/app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
  end

  def show
    begin
      @word = Word.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @word = nil
      flash.now[:alert] = "データベースにはid=#{params[:id]}のデータは登録されていません"
    end
  end    

  def new
    @word = Word.new
    @submit = "作成"
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      flash[:success] = "単語を保存しました"
      redirect_to @word, status: :see_other
    else
      flash.now[:alert] = "単語を保存できませんでした"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    begin
      @word = Word.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @word = nil
      flash[:alert] = "データベースにはid=#{params[:id]}のデータは登録されていません"
      redirect_to words_path, status: :see_other
    end
    @submit = "変更"
  end

  def update
    @word = Word.find(params[:id])
    if @word.update(word_params)
      redirect_to @word, status: :see_other
    else
      flash.now[:alert] = "単語「#{@word.en}」は変更できませんでした"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @word = Word.find(params[:id])
    if @word == nil
      flash[:alert] = "単語#{@en}は未登録のため削除できません"
    else
      begin
        @word.destroy
      rescue
        flash[:alert] = "単語#{@en}を削除できませんでした"
      else
        flash[:success] = "単語を削除しました"
      end
      redirect_to words_path, status: :see_other
    end
  end

  def search
    @search_word = params[:search]
    if @search_word == ""
      flash.now[:alert] = "検索ワードは入力必須です"
      render html: "", status: :unprocessable_entity
    end
    begin
      pattern = Regexp.compile(@search_word)
    rescue RegexpError
      flash.now[:alert] = "正規表現に構文エラーがあります"
      render :index, status: :unprocessable_entity
    else
      @words = Word.all.select{|word| word[:en] =~ pattern}.sort{|w1,w2| w1[:en] <=> w2[:en]}
    end
  end

  private

  def word_params
    params.require(:word).permit(:en, :jp, :note)
  end
end

_example/word_book_rails_resources/app/helpers/application_helper.rb
module ApplicationHelper
end

_example/word_book_rails_resources/app/helpers/words_helper.rb
module WordsHelper
end

_example/word_book_rails_resources/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordBookRailsResources</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <div class="col-lg-10 col-xl-8 mx-auto">
        <%= render "navbar" %>
        <%= render "flash" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

_example/word_book_rails_resources/app/views/words/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if name == "success" %>
    <%= content_tag :div, msg, class: "text-success" %>
  <% elsif name == "alert" %>
    <%= content_tag :div, msg, class: "text-danger" %>
  <% end %>
<% end %>

_example/word_book_rails_resources/app/views/words/_form.html.erb
<%= form_with model: @word do |form| %>
  <div>
    <%= form.label :en, "英単語", class: "form-label" %>
    <%= form.text_field :en, value: @word.en, class: "form-control" %>
    <% @word.errors.full_messages_for(:en).each do |message| %>
      <div class="text-danger"><%= "DB: 英単語は空欄にできません" if message == "En can't be blank" %></div>
      <div class="text-danger"><%= "DB: 英文字を入力してください" if message == "En is invalid" %></div>
      <div class="text-danger"><%= "DB: すでに同名の単語が登録されています" if message == "En has already been taken" %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :jp, "日本語訳", class: "form-label" %>
    <%= form.text_field :jp, value: @word.jp, class: "form-control" %>
    <% @word.errors.full_messages_for(:jp).each do |message| %>
      <div class="text-danger"><%= "DB: 日本語訳は空欄にできません" if message == "Jp can't be blank" %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :note, "備考", class: "form-label" %>
    <%= form.text_area :note, value: @word.note, class: "form-control" %>
    <% @word.errors.full_messages_for(:jp).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <% end %>
  </div>

  <div class="my-2">
    <%= form.submit @submit,  class: "btn btn-primary" %>
  </div>
<% end %>

_example/word_book_rails_resources/app/views/words/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Wordbook</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "追加", new_word_path, style: "text-decoration: none;", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if action_name == "show" && @word %>
            <%= link_to "変更", edit_word_path(@word), style: "text-decoration: none;", class: "nav-link" %>
          <% else %>
            <a class="nav-link disabled" href="#">変更</a>
          <% end %>
        </li>
        <li class="nav-item">
          <% if action_name == "show" && @word%>
            <%= link_to "削除", @word, style: "text-decoration: none;", class: "nav-link", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          <% else %>
            <a class="nav-link disabled" href="#">削除</a>
          <% end %>
        </li>
      </ul>
      <%= form_with  url: words_search_path, method: :get, class: "d-flex" do |form| %>
        <%= form.search_field :search, placeholder: "検索", class: "form-control me-2" %>
        <%= form.submit "検索", class: "btn btn-outline-success text-nowrap" %>
      <% end %>
    </div>
  </div>
</nav>

_example/word_book_rails_resources/app/views/words/edit.html.erb
<h1 class="my-2">単語の変更</h1>
<%= render "form" %>

_example/word_book_rails_resources/app/views/words/index.html.erb
<h1 class="text-center">単語帳</h1>
<h5 class="my-2">単語帳の使い方</h5>
<ul class="list-group my-2">
  <li class="list-group-item">Wordbook: 初期画面に戻ります</li>
  <li class="list-group-item">追加: 単語を追加します</li>
  <li class="list-group-item">検索: 単語を検索しマッチした単語を表示します</li>
</ul>
<p>
検索にRubyの正規表現を使うことができます。
各単語に対して「英単語」「日本語訳」「備考」を書き、保存することができます。
「備考」は複数行のテキストが可能なので、例文や解説などを書くのに適しています。
</p>
<p>
単語の表示、変更、削除は次のようにしてください。
なお「単語の表示」または「表示画面」とは、ひとつの単語についてその日本語訳と備考を表示すること、またはその画面です。
検索結果の画面では備考は表示されません。
</p>
<ul class="list-group my-2">
  <li class="list-group-item">表示: 検索後の一覧において、各項目の左にあるボタンをクリック</li>
  <li class="list-group-item">変更: 表示画面から変更メニューをクリック</li>
  <li class="list-group-item">削除: 表示画面から削除メニューをクリック</li>
</ul>

_example/word_book_rails_resources/app/views/words/new.html.erb
<h1 class="my-2">単語登録</h1>
<%= render "form" %>

_example/word_book_rails_resources/app/views/words/search.html.erb
<h1 class="my-2">単語検索結果</h1>
<p>検索ワード: <%= @search_word %></p>
<% if @words %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">英語</th>
        <th scope="col">日本語</th>
      </tr>
    </thead>
    <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= link_to word[:en], word %></td>
        <td><%= word[:jp] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

_example/word_book_rails_resources/app/views/words/show.html.erb
<% if @word %>
  <ul class="list-group my-2">
    <li class="list-group-item"><%= @word.en %></li>
    <li class="list-group-item"><%= @word.jp %></li>
    <li class="list-group-item"><%= @word.note %></li>
  </ul>
<% end %>